services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami/kafka
    environment:
      - KAFKA_KRAFT_CLUSTER_ID=Rhz2EA63T_W214c1iBnu9Q
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9094
      - KAFKA_CFG_LISTENERS=INTERNAL://:9093,EXTERNAL://:9092,CONTROLLER://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9093,EXTERNAL://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.d/admin-user.xml
    environment:
      - CLICKHOUSE_INIT_USER=admin
      - CLICKHOUSE_INIT_PASSWORD=admin
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  spark-master:
    image: custom-spark:3.4.1
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      clickhouse:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ~/.ivy2:/home/spark/.ivy2
      - ./spark:/opt/bitnami/spark/work-dir


  spark-worker:
    image: custom-spark:3.4.1
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    depends_on:
      spark-master:
        condition: service_started # ou service_healthy si vous en ajoutez un
      clickhouse:
        condition: service_healthy
    volumes:
      - ~/.ivy2:/home/spark/.ivy2
      - ./spark:/opt/bitnami/spark/work-dir


  superset:
    image: apache/superset
    container_name: superset
    ports:
      - "8088:8088"
    depends_on:
      - clickhouse
    environment:
      - SUPERSET_SECRET_KEY='xOvhA1P3n3sL9+bC/dEaG7hJkF8iN6mR5tYwU2zV0cQ4bE7lP='
    volumes:
      - superset_data:/app/superset_home
    command: >
      bash -c "
        pip install 'clickhouse-sqlalchemy==0.2.6' 'sqlalchemy<2.0' &&
        superset db upgrade &&
        superset fab create-admin --username admin --firstname Admin --lastname admin --email admin@superset.com --password admin &&
        superset init &&
        superset run -h 0.0.0.0 -p 8088"

volumes:
  kafka_data:
  superset_data:
